### ISSUE TITLE
Datumstempel

### ISSUE THREAD

**Issue by Zeroks77** [AC-Fernglas/AC-Configbuilder#14]
Dein Datumstempel ist sehr umständlich, such mal im Internet nach der richtigen Formatierung nach der DIN

**Comment by Zeroks77** [comment]
Alphabetisch sortierbar wäre nice

**Comment by paule96** [comment]
look at this:
https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=netcore-2.2
